import { useCallback, useEffect, useState } from 'react'
import { ChevronDown, ChevronUp, Heart, MessageCircle, Monitor, Phone, Share2, Smartphone } from 'lucide-react'
import { listings, related } from '../features/reels/data/listings'
import { Details } from '../features/reels/components/Details'
import { IconButton } from '../features/reels/components/IconButton'
import { ShareDialog } from '../features/reels/components/ShareDialog'
import { StateView } from '../features/reels/components/States'
import { VideoStage } from '../features/reels/components/VideoStage'
import type { DemoState, ViewMode } from '../features/reels/types'

export function App(){
 const [view,setView]=useState<ViewMode>('mobile'),[demo,setDemo]=useState<DemoState>('live'),[index,setIndex]=useState(0),[muted,setMuted]=useState(true),[details,setDetails]=useState(false),[share,setShare]=useState(false),[expanded,setExpanded]=useState(false),[favorites,setFavorites]=useState<Set<string>>(()=>new Set())
 const listing=listings[index]
 const navigate=useCallback((n:number)=>{setIndex(i=>(i+n+listings.length)%listings.length);setDetails(false);setExpanded(false)},[])
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==='ArrowDown'||e.key==='ArrowRight')navigate(1);if(e.key==='ArrowUp'||e.key==='ArrowLeft')navigate(-1);if(e.key.toLowerCase()==='m')setMuted(v=>!v)};addEventListener('keydown',onKey);return()=>removeEventListener('keydown',onKey)},[navigate])
 const toggleFavorite=()=>setFavorites(old=>{const next=new Set(old);if(next.has(listing.id)) next.delete(listing.id);else next.add(listing.id);return next})
 return <div className="app"><header className="toolbar"><div className="brand"><img src="/4sale-logo.png" alt="4Sale"/><span>/ reels</span></div><div className="segmented"><button className={view==='mobile'?'active':''} onClick={()=>setView('mobile')}><Smartphone/>Mobile</button><button className={view==='desktop'?'active':''} onClick={()=>setView('desktop')}><Monitor/>Desktop</button></div><div className="spacer"/><div className="segmented segmented--state">{(['live','loading','empty','error'] as DemoState[]).map(x=><button key={x} className={demo===x?'active':''} onClick={()=>setDemo(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div></header>
 <main>{demo!=='live'?<StateView state={demo} view={view} onRetry={()=>setDemo('live')}/>:view==='mobile'?<div className="phone"><div className="browserbar"><i/><i/><span>🔒 q84sale.com/reels</span></div><div className="phone__content"><VideoStage listing={listing} muted={muted} onMute={()=>setMuted(v=>!v)} onNavigate={navigate}/><span className="index">{index+1} / {listings.length}</span><div className="action-rail"><IconButton icon={Heart} label={listing.favCount} active={favorites.has(listing.id)} onClick={toggleFavorite}/><IconButton icon={Share2} label="Share" onClick={()=>setShare(true)}/><IconButton icon={MessageCircle} label="Chat"/><IconButton icon={Phone} label="Call" primary/></div>{!details?<button className="view-details" onClick={()=>setDetails(true)}><ChevronUp/>View details · <b>KD {listing.price}</b></button>:<div className="sheet"><button className="sheet__close" onClick={()=>setDetails(false)}><ChevronDown/></button><Details listing={listing} expanded={expanded} onExpand={()=>setExpanded(v=>!v)} onShare={()=>setShare(true)} favorite={favorites.has(listing.id)} onFavorite={toggleFavorite}/></div>}</div></div>:<div className="desktop"><nav><img src="/4sale-logo.png" alt="4Sale"/>{['⌂','▤','♡','◯','⚙'].map(x=><button key={x}>{x}</button>)}</nav><section className="desktop__video"><VideoStage listing={listing} muted={muted} onMute={()=>setMuted(v=>!v)} onNavigate={navigate}/><div className="desktop__rail"><IconButton icon={Heart} label={listing.favCount} active={favorites.has(listing.id)} onClick={toggleFavorite}/><IconButton icon={Share2} label="Share" onClick={()=>setShare(true)}/><IconButton icon={MessageCircle} label="Chat"/><IconButton icon={Phone} label="Call" primary/></div><div className="progress"><i style={{height:`${(index+1)/listings.length*100}%`}}/></div></section><aside><Details listing={listing} expanded={expanded} onExpand={()=>setExpanded(v=>!v)} onShare={()=>setShare(true)} favorite={favorites.has(listing.id)} onFavorite={toggleFavorite}/><h2 className="related-title">You may also like</h2><div className="related">{related.map((x,i)=><article key={x}><div/><small>{x}</small><b>KD {(10900+i*850).toLocaleString()}</b></article>)}</div></aside></div>}</main>{share?<ShareDialog id={listing.id} onClose={()=>setShare(false)}/>:null}</div>
}
